### ISSUE TITLE
请问作者能支持达梦里的事务和回滚吗？感谢

### ISSUE THREAD

**Issue by sdhou** [li1125435097/typeorm-dmdb8#1]
请问作者能支持达梦里的事务和回滚吗？感谢

**Comment by li1125435097** [comment]
我们之前的项目是用mariadbab做数据库的。我写这个库是为了对接国产化达梦数据库。里面有一些mariadbab查询语句定制化转换。你们要是从别的数据库比如Oracle转过来的，可能不太适配，需要你把源码拉个分支自己再做个兼容。
理论上我做了typeORM框架实现，和别的数据库一样是支持事务的

**Comment by sdhou** [comment]
知道了 謝謝
